### ISSUE TITLE
Allowing orphan entries to be rendered based on position in the list and not at the bottom

### ISSUE THREAD

**Issue by Mikayl** [BigBasket/ra-treemenu#11]
**Is your feature request related to a problem? Please describe.**
I have the "important" routes first and then I have the less "important" stuff that I want to group together at the bottom. The way the code is implemented now all orphans are rendered last and this seems to be an unnecesary restriction. 
Example of what i want to be possible:
[https://imgur.com/a/uzudeL4](url)

**Describe the solution you'd like**
The solution (that I already implemented) would not really change the code in significant ways, instead of going over the parents and then orphans it just goes over them all and renders them like this:

`    resources.forEach(r => {
        if(isParent(r)){
            resRenderGroup.push(mapParent(r))
        }
        if(isOrpahn(r)) {
            resRenderGroup.push(mapIndependent(r))
        }
    });`
Giving users the option to chose the placement seems the best option without having any downsides that I can spot now.

If you are interested into the idea I could try and clean&prepare a PR. 

Cheers.

**Comment by harshit-budhraja** [comment]
Hi @Mikayl. This solution looks good and pretty empathising in a way that we're giving users an extended flexibility to chose their own order. Could you please raise a PR for the same?
Thanks.

**Comment by Mikayl** [comment]
Glad to hear it, will get it ready soon.

Thanks.
