### ISSUE TITLE
Missing key prop on parent resource.

### ISSUE THREAD

**Issue by BlazHrusovar** [BigBasket/ra-treemenu#12]
**Describe the bug**
There's a missing key prop on the parent resource.

**Screenshots**
![image](https://user-images.githubusercontent.com/18646004/93858385-62365300-fcbc-11ea-927c-a1d732ae6fbb.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0

**Additional context**
In the index.modern.js, line 381. The child element does not have a key specified.

**Comment by harshit-budhraja** [comment]
@BlazHrusovar Could you please paste the stack trace of the error that you see in the browser console?

**Comment by BlazHrusovar** [comment]
@harshit-budhraja Hey, thanks for replying. That is the complete stack trace.

![image](https://user-images.githubusercontent.com/18646004/93878426-58bbe380-fcda-11ea-9cd4-fcccea7354b9.png)

I think this list of elements are missing the key attribute.

![image](https://user-images.githubusercontent.com/18646004/93878723-d4b62b80-fcda-11ea-9630-ec1e931ace45.png)
