### ISSUE TITLE
Non Menu resources are listed as Menu Items

### ISSUE THREAD

**Issue by deeptha-as** [BigBasket/ra-treemenu#15]
**Describe the bug**
I would like to define additional resources apart from those that I want to list as menu items. Currently, all the resources are rendered as menu items. I want to render menu items based on the 'list' property similar to react-admin and define additional resources as well.

The menu items are displayed like the below screenshot.
![D2D34866-3ED3-41F8-805F-D6ABBA6AE032](https://user-images.githubusercontent.com/48817623/95735556-95a84400-0ca2-11eb-8f4a-c2737407485b.png)

**Solution**
The solution that I implemented is add an additional condition while rendering the orphan entries to check the hasList value of the resource.

resources.filter(r => r.options && !r.options.hasOwnProperty('menuParent') && !r.options.hasOwnProperty('isMenuParent') && r.hasList)

**Comment by harshit-budhraja** [comment]
Hi @deeptha-as !! Thank you so much for pointing out this to us. We've fixed this and the same will be a part of the upcoming milestone release 1.0.3. Ref: #10
