### ISSUE TITLE
Blank Screen on opening react-admin after integrating ra-treemenu

### ISSUE THREAD

**Issue by harshit-budhraja** [BigBasket/ra-treemenu#18]
**Describe the bug**
Default resource routed in RA applications using ra-treemenu is the parent resource which is a dummy. This is happening only when the first resource actually contains a parent i.e. is not orphan.

**To Reproduce**
1. Run RA application server.
2. Open http://localhost:3000 in the browser.
3. You'll see a blank page. On checking the url, the bug could be noticed and explained.

**Screenshots**

![image](https://user-images.githubusercontent.com/52413945/97667827-bfd17280-1aa6-11eb-98c7-19baf8c73fdc.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (x86_64)

**Comment by sivaavkd** [comment]
It is recommended to use either dashboard or an orphan page

**Comment by sivaavkd** [comment]
closing this for now since we have - 1) a working alternate and 2) the solution may need changes to dashboard of react-admin
