### ISSUE TITLE
Console error: Warning, Mission translation for key: "..."

### ISSUE THREAD

**Issue by BlazHrusovar** [BigBasket/ra-treemenu#20]
**Describe the bug**
I noticed I am getting console errors with the new update. If I do not use translations on my labels, I will receive this error for every resource that I use. 

eg. I am using an User resource like this:
`<Resource icon={UsersIcon} options={{ label: 'Users', menuParent: "usersParent" }} name='users' list={UserList} show={UserShow} edit={UserEdit} create={UserCreate} />,`
and because I am not using translations since my label is hardcoded I am getting the "Warning, Mission translation for key: "Users" error.

**To Reproduce**
Use a resource without a translated label.

**Screenshots**
![error](https://user-images.githubusercontent.com/18646004/99073163-b4596d80-25b5-11eb-9587-52887f6f6f15.JPG)

**Environment (please complete the following information):**
 - Windows 10
 - Chrome 
 - Version 86.0.4240.111

I hope I was as clear as possible. If you have any additional questions, please ask away.

**Comment by harshit-budhraja** [comment]
@BlazHrusovar: Can you please mention the `ra-treemenu` version that you're using in your `package.json`?

**Comment by BlazHrusovar** [comment]
@harshit-budhraja Sure. I am using version 1.0.4.

**Comment by yusney** [comment]
I have the same problem and use the same version 1.0.4

**Comment by erheme318** [comment]
I silenced the translation warnings by following [this documentation](https://github.com/marmelab/react-admin/blob/master/docs/Translation.md#silencing-translation-warnings)

**Comment by harshit-budhraja** [comment]
@BlazHrusovar @yusney As aptly pointed out by @erheme318, translations, at this moment,  are supposed to be taken care of from within the i18Provider in the RA app and this is why any externally packaged components don't have access to the i18Provider's objects directly. So, silencing the translation messages for now looks like the best solution. Meanwhile, we can come up with a legitimate fix for these warnings.

https://github.com/marmelab/react-admin/blob/master/docs/Translation.md#silencing-translation-warnings

**Comment by BlazHrusovar** [comment]
@harshit-budhraja @erheme318 This worked. Thanks guys.
