### ISSUE TITLE
No label will be displayed if it's not set explicitly

### ISSUE THREAD

**Issue by Koli14** [BigBasket/ra-treemenu#22]
**Describe the bug**

No label will be displayed for 'normal' `<Resource>` components, if it's not set explicitly. 
E.g.: See official example: 
`<Resource name="posts" list={PostList} icon={PostIcon} />` ([Docs](https://marmelab.com/react-admin/Resource.html))
Should have a label 'Posts'.

**To Reproduce**
1. Go to [this](https://codesandbox.io/s/react-admin-v3-advanced-recipes-managing-user-profile-forked-0vg26?file=/src/MyLayout.js) CodeSandbox, what I forked from an [Offical CodeSandbox](https://codesandbox.io/s/react-admin-v3-advanced-recipes-managing-user-profile-qcql4)
2. Toggle the menu, if it's not visible, and see, there are no labels by the Resources in the Menu.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/400223/117965775-700c1780-b323-11eb-9110-515f985b518c.jpg)

**Environment (please complete the following information):**
 - OS: Windows (i know, it's a shame, but the company don't let me working on Linux/Mac :P)
 - Firefox + Chrome
 - Node: v14.16.1
 - NPM: 6.14.12
 - react: "^17.0.2"
 - react-admin: "^3.15.1"
  - react-dom: "^17.0.2"
 - @bb-tech/ra-treemenu: "^1.0.4"

**Comment by sivaavkd** [comment]
fixed in 1.0.5
