### ISSUE TITLE
Required runtime dependency 'recompose' not listed in dependencies

### ISSUE THREAD

**Issue by cubabit** [BigBasket/ra-treemenu#7]
**Describe the bug**
You get a runtime error that recompose/compose cannot be resolved.

**To Reproduce**
1. Install minimal setup: CRA and RA, then install this module
2. npm start

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser N/A - error is in webpack
 - Version 1.0.0

**Comment by harshit-budhraja** [comment]
Fixed runtime dependency issue with recompose due to [BC Break] removal of its dependency in react-admin `>=3.8.0` with release `1.0.2`. Closing this issue.
cc: @cubabit
